"""
Rule: DirectX Shader Cache & GPU Caches
Scans D3DSCache, NVIDIA, AMD, and Intel shader caches.
These are auto-regenerated by the GPU driver and DirectX runtime.
"""

from __future__ import annotations

import os
from models import CleanupCategory, CleanupItem, RiskLevel, ItemType

name = "shader_cache"
display_name = "GPU & Shader Caches"
description = "DirectX shader cache, NVIDIA/AMD/Intel GPU caches (auto-regenerated)"
risk = RiskLevel.SAFE


def scan() -> CleanupCategory:
    category = CleanupCategory(
        name=display_name,
        description=description,
        risk=risk,
    )

    localappdata = os.environ.get("LOCALAPPDATA", "")
    appdata = os.environ.get("APPDATA", "")
    programdata = os.environ.get("PROGRAMDATA", r"C:\ProgramData")

    # ── DirectX Shader Cache ─────────────────────────────────────────────
    if localappdata:
        d3ds_cache = os.path.join(localappdata, "D3DSCache")
        _add_dir(category, d3ds_cache, "DirectX shader cache", RiskLevel.SAFE)

    # ── NVIDIA caches ────────────────────────────────────────────────────
    if localappdata:
        nvidia_gl = os.path.join(localappdata, "NVIDIA", "GLCache")
        _add_dir(category, nvidia_gl, "NVIDIA OpenGL shader cache", RiskLevel.SAFE)

        nvidia_dx = os.path.join(localappdata, "NVIDIA", "DXCache")
        _add_dir(category, nvidia_dx, "NVIDIA DirectX shader cache", RiskLevel.SAFE)

    if appdata:
        nvidia_compute = os.path.join(appdata, "NVIDIA", "ComputeCache")
        _add_dir(category, nvidia_compute, "NVIDIA compute cache", RiskLevel.SAFE)

    if programdata:
        nvidia_logs = os.path.join(programdata, "NVIDIA Corporation", "Downloader")
        _add_dir(category, nvidia_logs, "NVIDIA driver downloader cache", RiskLevel.SAFE)

    # ── AMD caches ───────────────────────────────────────────────────────
    if localappdata:
        amd_gl = os.path.join(localappdata, "AMD", "GLCache")
        _add_dir(category, amd_gl, "AMD OpenGL shader cache", RiskLevel.SAFE)

        amd_dx = os.path.join(localappdata, "AMD", "DxCache")
        _add_dir(category, amd_dx, "AMD DirectX shader cache", RiskLevel.SAFE)

        amd_dx9 = os.path.join(localappdata, "AMD", "DxcCache")
        _add_dir(category, amd_dx9, "AMD DXC shader cache", RiskLevel.SAFE)

    # ── Intel caches ─────────────────────────────────────────────────────
    if localappdata:
        intel_shader = os.path.join(localappdata, "Intel", "ShaderCache")
        _add_dir(category, intel_shader, "Intel shader cache", RiskLevel.SAFE)

    return category


def _add_dir(category: CleanupCategory, dir_path: str, label: str, risk: RiskLevel) -> None:
    if not os.path.isdir(dir_path):
        return
    size = _dir_size(dir_path)
    if size > 0:
        category.items.append(CleanupItem(
            path=dir_path,
            size=size,
            category=category.name,
            risk=risk,
            item_type=ItemType.DIRECTORY,
            description=label,
        ))


def _dir_size(path: str) -> int:
    total = 0
    try:
        for dirpath, _, filenames in os.walk(path):
            for f in filenames:
                try:
                    total += os.path.getsize(os.path.join(dirpath, f))
                except (OSError, PermissionError):
                    pass
    except (OSError, PermissionError):
        pass
    return total
